name: Dev Polybot Service Deployment

on:
  push:
    branches:
      - dev

env:
  EC2_PUBLIC_IP: 18.216.187.161
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  Deploy:
    name: Deploy in EC2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the app code
        uses: actions/checkout@v2
      - name: SSH to EC2 instance
        run: |
            echo "$SSH_PRIVATE_KEY" > mykey.pem
            chmod 400 mykey.pem
            ssh -i mykey.pem -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP << 'EOF'
            cd /home/ubuntu/PolybotServicePythonFursa/polybot
            source venv/bin/activate
            git pull origin dev
            sudo systemctl restart polybot.service
          EOF
